DROP TABLE IF EXISTS TB_HEROIS;
CREATE TABLE TB_HEROIS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER TEXT NOT NULL
)

--create
INSERT INTO TB_HEROIS(NOME, PODER)
VALUES
('Flash', 'Velocidade'),
('Aquaman', 'Falar com os animais'),
('Batman', 'Dinheiro')

--read
SELECT * FROM TB_HEROIS;
SELECT * FROM TB_HEROIS where nome = 'Flash';

--update
UPDATE TB_HEROIS
SET NOME = 'Goku', PODER = 'Deus'
where id = 1;

--DELETE
DELETE FROM TB_HEROIS WHERE ID = 2; 
